# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sonal/Desktop/vlsi-arch/project/cordic_implementation/cordic_pipeline/cordic_pipeline.cache/wt [current_project]
set_property parent.project_path /home/sonal/Desktop/vlsi-arch/project/cordic_implementation/cordic_pipeline/cordic_pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo /home/sonal/Desktop/vlsi-arch/project/cordic_implementation/cordic_pipeline/cordic_pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/sonal/Desktop/vlsi-arch/project/cordic_implementation/verilog_files/pipeline/shift_accumulate.v
  /home/sonal/Desktop/vlsi-arch/project/cordic_implementation/verilog_files/pipeline/cordic_updated.v
  /home/sonal/Desktop/vlsi-arch/project/cordic_implementation/verilog_files/pipeline/cordic_tb_updated.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sonal/Desktop/vlsi-arch/project/cordic_implementation/cordic_pipeline/cordic_pipeline.srcs/constrs_1/new/trial.xdc
set_property used_in_implementation false [get_files /home/sonal/Desktop/vlsi-arch/project/cordic_implementation/cordic_pipeline/cordic_pipeline.srcs/constrs_1/new/trial.xdc]


synth_design -top cordic_tb_updated -part xc7z020clg484-1


write_checkpoint -force -noxdef cordic_tb_updated.dcp

catch { report_utilization -file cordic_tb_updated_utilization_synth.rpt -pb cordic_tb_updated_utilization_synth.pb }
